const questions = [
  // --- 1-15: Grammar Focus (Tense, Parts of Speech, Prep) ---
  { "id": 1, "category": "Mixed English", "question": "Somsak _______ to the gym every evening.", "options": ["go", "goes", "going", "gone"], "answerIndex": 1 },
  { "id": 2, "category": "Mixed English", "question": "I _______ my keys in the car yesterday.", "options": ["leave", "leaves", "left", "leaving"], "answerIndex": 2 },
  { "id": 3, "category": "Mixed English", "question": "She is _______ than her sister.", "options": ["tall", "taller", "tallest", "more tall"], "answerIndex": 1 },
  { "id": 4, "category": "Mixed English", "question": "We have lived here _______ 2010.", "options": ["for", "since", "during", "at"], "answerIndex": 1 },
  { "id": 5, "category": "Mixed English", "question": "There isn't _______ milk in the fridge.", "options": ["some", "any", "many", "a few"], "answerIndex": 1 },
  { "id": 6, "category": "Mixed English", "question": "Look! The police _______ after the thief.", "options": ["run", "is running", "are running", "runs"], "answerIndex": 2 },
  { "id": 7, "category": "Mixed English", "question": "If I _______ a bird, I would fly to you.", "options": ["am", "was", "were", "be"], "answerIndex": 2 },
  { "id": 8, "category": "Mixed English", "question": "You _______ park here. It's a no-parking zone.", "options": ["can", "must", "mustn't", "should"], "answerIndex": 2 },
  { "id": 9, "category": "Mixed English", "question": "The report _______ by the manager tomorrow.", "options": ["will finish", "will be finished", "finishes", "finished"], "answerIndex": 1 },
  { "id": 10, "category": "Mixed English", "question": "He speaks English _______.", "options": ["good", "well", "fluent", "slow"], "answerIndex": 1 },
  { "id": 11, "category": "Mixed English", "question": "I'm interested _______ learning Thai culture.", "options": ["at", "on", "in", "with"], "answerIndex": 2 },
  { "id": 12, "category": "Mixed English", "question": "Whose bag is this? It's _______.", "options": ["me", "my", "mine", "myself"], "answerIndex": 2 },
  { "id": 13, "category": "Mixed English", "question": "They didn't go out _______ it was raining.", "options": ["but", "because", "so", "although"], "answerIndex": 1 },
  { "id": 14, "category": "Mixed English", "question": "She _______ her homework when I called her.", "options": ["did", "does", "was doing", "is doing"], "answerIndex": 2 },
  { "id": 15, "category": "Mixed English", "question": "You like coffee, _______?", "options": ["do you", "don't you", "are you", "aren't you"], "answerIndex": 1 },

  // --- 16-25: Vocabulary Focus (General & Police) ---
  { "id": 16, "category": "Mixed English", "question": "The synonym of 'Quick' is _______.", "options": ["Slow", "Fast", "Quiet", "Heavy"], "answerIndex": 1 },
  { "id": 17, "category": "Mixed English", "question": "A _______ is a person who defends people in court.", "options": ["Police", "Judge", "Lawyer", "Witness"], "answerIndex": 2 },
  { "id": 18, "category": "Mixed English", "question": "Which word is the opposite of 'Dangerous'?", "options": ["Risky", "Safe", "Scary", "Hard"], "answerIndex": 1 },
  { "id": 19, "category": "Mixed English", "question": "You should _______ the door before leaving.", "options": ["lock", "open", "break", "knock"], "answerIndex": 0 },
  { "id": 20, "category": "Mixed English", "question": "The police found some _______ at the crime scene.", "options": ["evidence", "exercise", "education", "energy"], "answerIndex": 0 },
  { "id": 21, "category": "Mixed English", "question": "I am so _______; I want to drink some water.", "options": ["hungry", "tired", "thirsty", "angry"], "answerIndex": 2 },
  { "id": 22, "category": "Mixed English", "question": "The idiom 'a piece of cake' means _______.", "options": ["delicious", "very easy", "expensive", "very hard"], "answerIndex": 1 },
  { "id": 23, "category": "Mixed English", "question": "The officer asked the driver for his _______.", "options": ["passport", "ID card", "license", "ticket"], "answerIndex": 2 },
  { "id": 24, "category": "Mixed English", "question": "What is the antonym of 'Strong'?", "options": ["Power", "Weak", "Fast", "Heavy"], "answerIndex": 1 },
  { "id": 25, "category": "Mixed English", "question": "To 'investigate' a case means to _______.", "options": ["ignore", "find the truth", "forget", "start a fire"], "answerIndex": 1 },

  // --- 26-40: Conversation Focus (Situational) ---
  { "id": 26, "category": "Mixed English", "question": "A: How are you? \nB: _______.", "options": ["I'm fine, thanks", "I'm a student", "Nice to meet you", "Goodbye"], "answerIndex": 0 },
  { "id": 27, "category": "Mixed English", "question": "A: Excuse me, where is the bank? \nB: _______.", "options": ["It's on your left", "Yes, it is", "I'm a banker", "No, thank you"], "answerIndex": 0 },
  { "id": 28, "category": "Mixed English", "question": "A: Could you help me with this? \nB: _______.", "options": ["No problem", "You're welcome", "I'm sorry", "Goodbye"], "answerIndex": 0 },
  { "id": 29, "category": "Mixed English", "question": "A: Thank you very much. \nB: _______.", "options": ["Never mind", "You're welcome", "Please", "It's okay"], "answerIndex": 1 },
  { "id": 30, "category": "Mixed English", "question": "A: Nice to meet you. \nB: _______.", "options": ["Nice to meet you, too", "How do you do", "Fine", "See you"], "answerIndex": 0 },
  { "id": 31, "category": "Mixed English", "question": "A: May I use your pen? \nB: _______.", "options": ["Yes, please", "Sure, here it is", "No, I don't", "It's a pen"], "answerIndex": 1 },
  { "id": 32, "category": "Mixed English", "question": "A: What's the matter? \nB: _______.", "options": ["I have a headache", "I'm from Japan", "I'm 20", "It's 5 o'clock"], "answerIndex": 0 },
  { "id": 33, "category": "Mixed English", "question": "A: Would you like some tea? \nB: _______, I'm thirsty.", "options": ["No, thanks", "Yes, please", "I'm sorry", "Never mind"], "answerIndex": 1 },
  { "id": 34, "category": "Mixed English", "question": "A: I'm sorry for being late. \nB: _______.", "options": ["Don't worry about it", "You're welcome", "Yes, you are", "I'm fine"], "answerIndex": 0 },
  { "id": 35, "category": "Mixed English", "question": "A: Hello, may I speak to John? \nB: _______.", "options": ["Hold on, please", "I'm John", "Who are you?", "He is out"], "answerIndex": 0 },
  { "id": 36, "category": "Mixed English", "question": "A: How far is it from here? \nB: _______.", "options": ["About 10 minutes", "About 2 kilometers", "It's very far", "Yes, it is"], "answerIndex": 1 },
  { "id": 37, "category": "Mixed English", "question": "A: What time is the meeting? \nB: _______.", "options": ["At 9:00 AM", "In the room", "With the boss", "Yesterday"], "answerIndex": 0 },
  { "id": 38, "category": "Mixed English", "question": "A: Have a safe trip! \nB: _______.", "options": ["You too", "Thank you", "Goodbye", "All of above"], "answerIndex": 3 },
  { "id": 39, "category": "Mixed English", "question": "A: How do you do? \nB: _______.", "options": ["I'm fine", "How do you do?", "Nice to meet you", "Good morning"], "answerIndex": 1 },
  { "id": 40, "category": "Mixed English", "question": "A: Can I give you a hand? \nB: _______.", "options": ["Yes, please", "No, I don't", "It's my hand", "I'm sorry"], "answerIndex": 0 },

  // --- 41-50: Reading Focus (Signs & Short Passage) ---
  { "id": 41, "category": "Mixed English", "question": "A sign says: 'NO ENTRY'. What does it mean?", "options": ["You can go in", "You must not go in", "Exit only", "Free parking"], "answerIndex": 1 },
  { "id": 42, "category": "Mixed English", "question": "A label says: 'KEEP COLD'. Where should you store it?", "options": ["In the oven", "In the fridge", "In a box", "Outside"], "answerIndex": 1 },
  { "id": 43, "category": "Mixed English", "question": "Ad: 'Buy 1 Get 1 Free'. This is a _______.", "options": ["Job ad", "Promotion", "Warning", "Notice"], "answerIndex": 1 },
  { "id": 44, "category": "Mixed English", "question": "A sign says: 'SILENCE'. Where would you see this?", "options": ["At a concert", "In a library", "At a market", "In a gym"], "answerIndex": 1 },
  { "id": 45, "category": "Mixed English", "question": "Ad: 'WANTED: Part-time waiter'. This is for a _______.", "options": ["School", "Job", "Room", "Movie"], "answerIndex": 1 },
  { "id": 46, "category": "Mixed English", "question": "Passage: 'The police arrested a thief at the mall.' Where did it happen?", "options": ["At home", "At the mall", "At the station", "At the bank"], "answerIndex": 1 },
  { "id": 47, "category": "Mixed English", "question": "Sign: 'FRAGILE'. Be careful because it _______.", "options": ["is heavy", "breaks easily", "is expensive", "is dirty"], "answerIndex": 1 },
  { "id": 48, "category": "Mixed English", "question": "Email Subject: 'RSVP'. What does the sender want?", "options": ["Money", "A reply", "A gift", "A photo"], "answerIndex": 1 },
  { "id": 49, "category": "Mixed English", "question": "Passage: 'Exercising every day makes you healthy.' What is the benefit?", "options": ["Getting rich", "Good health", "Better sleep", "More friends"], "answerIndex": 1 },
  { "id": 50, "category": "Mixed English", "question": "Sign: 'OUT OF ORDER'. Can you use this machine?", "options": ["Yes", "No", "Maybe", "Only staff"], "answerIndex": 1 }
];
